spring:
  application:
    name: weather
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost:3306/weather_db?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true"
    username: root
    password: test
  liquibase:
    change-log: "classpath:liquibase/db/changelog/changelog-current.xml"
    enabled: true
server:
  port: 8080
management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: true
    web:
      base-path: '/'
      exposure:
        include: '*'
  info.env.enabled: true
